### ISSUE TITLE
Barcos - Passagem de um mapa para o outro

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#100]
Anticheat deteta como click-to-move.

**Comment by Psychh** [comment]
100#

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
