### ISSUE TITLE
Não uso Two-factor authentication

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#101]
Devia tentar ver https://github.com/settings/two_factor_authentication/intro

Isso e não guardar passwords do website assim por extenso. Podia ter sido bitbucket :)

I just wannatest, like 123
Isto não é phishing oh nabo... Quem precisa de phishing se basta ver as passwords escritas por extenso...
mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Ja agora o barco de Booty Bay para Ratchet está estranho. Devias ver o que se passa.
Ainda dá para usar double jump por cima de água, ainda da para atravessar paredes/teleportes de 3 yards.
Trackings multiplos não são detetados pelo server.
Consegui ir para GMIsland e passear lá um pouco, o teleporte de volta para booty bay pode ter pequeno bypass.
http://i.imgur.com/iWXen4T.jpg

**Comment by silvermcd123** [comment]
Já agora, não devias usar a mesma password para todo o lado, devias também ter alterado esta pword 🥇
