### ISSUE TITLE
Website - GMPanel alternar entre contas e chars

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#11]
Possibilidade de abrir diretamente uma conta atraves da página de uma personagem e vice-versa.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
