### ISSUE TITLE
Arguz has failed his mission

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#114]
Can't be fixed at all

**Comment by silvermcd123** [comment]
I wannatest arguz but he has no scripts at all.

**Comment by silvermcd123** [comment]
FACTS

- [ ] Screenshots de 1991 na gmisland gonna be fake

- [ ] Posts de 1991 da fraglider não provam a tua palavra, apenas estás a dar continuidade á tua bloodline.

- [ ] A minha vida pessoal tá publica, how about yours? oh nvm, não a tens, na boa, Tiago Santos, agora percebo a relação.

- [ ] Teres "hackeado" o github ás custas de uma falha minha e com a ajuda de um leak do sr.willer não conta como ser hacker (ps: manda-lhe um abraço de minha parte).

- [ ] Screenshots de um evento que nunca foi sequer iniciado debaixo de karazhan numa screenshot de 1991 não faz de ti pro 1337.

- [ ] Fazer uma função random para provar algo que ninguem sabe o que no fundo, dares um fail ao comentar a chaveta final, coloca as tuas programming skillz ao nivel das minhas paint skillz.

- [ ] E por fim, tanto hate e tanta vontade de lixar a vida dos outros, faz de ti um no lifer á quantidade de issues que colocaste aqui para no fim o github staff me colocar tudo de volta ;)

- [ ] E já agora, podes-me devolver a conta? OHHHH wait... i see.... preciso pedir com jeitinho?

**Comment by ThisAintMeSilver** [comment]
1991?
Não "hackeei", nunca disse que o fiz, o willier nada teve a ver com isso, lembras-te que já tive acesso a DB? Estava lá tudo silver, já há vários anos que a password não era mudada. Quando o willier descobriu ele não me disse qual era, eu apenas lhe perguntei se ainda acabava em 123 e ele disse que sim. Usar mesma password para todas as tuas contas não é boa ideia, tu sabes bem disso.

A função em questão tinha um bug, conseguiste descobri-lo? Até o nome daquilo era Random Function, com tag Bug. 
`if getRandomNumber(){ return 4; //Consegues Perceber que se ensina isto no primeiro dia? }`
Ainda bem que a staff recuperou tudo integralmente, nunca foi objetivo meu remover os issues. 
Tive mais de 30 clicks naquele link, mais que meus "fanboys", ao menos levei-te a meter o server mais seguro contra estas ferramentas. Em relação ao Teamspeak, está também mais seguro, coisa que te venho a sugerir a algum tempo. Portanto sim, podes dizer GJ, levei-te a fazer algo que já devias ter feito a mais tempo.

Em relação a conta, sim, recuperaste. Btw fui eu que a apaguei uma hora ou duas depois de te ires embora do teamspeak, por estar farto desta palhaçada e da maneira como atuei (apenas em parte, mereceste pelo facto de mesmo depois do willier ter descoberto continuares com a mesma)


Btw de todos os issues criados, o da Lady Vashj é verdadeiro, está mesmo a crashar o server, isso ou foi o teu evento de pve.

**Comment by ThisAintMeSilver** [comment]
Ja percebi o 1991. Btw devias testar usar as "ferramentas" que eu pus juntamente com uma mota dos teus eventos. Não está a ser detetado.

**Comment by silvermcd123** [comment]
https://github.com/silvermcd123/WOWPT/issues/82
Talvez tenha-te escapado isto, a lady vashj não está a crashar o server desde o dia 6. estás uma beca atrasado. btw, o percevejo é um gm (just a fact). a tua screenshot da gmisland é antiga (antes do fix) e as ferramentas efetivamente não funcionam (testei tudo, com o AC ligado).
Quanto ao saberes a minha passe, nunca a passe da db foi a minha passe pessoal (e muito menos duvido que consigas desencriptar um MD5), a minha passe pessoal foi leaked junto a db q o willier fez questão de dar upload na altura (porque nos tinhamos um script no website onde colocavamos as passes, sem ser encriptadas, numa tabela, na altura q eras gm, isso não existia). tenho muitas contas sim :) esqueci-me desta, a gravidade de teres tido acesso a isto foi pouca ou quase nula.

**Comment by silvermcd123** [comment]
e sim, obviamente que eu percebi a cena do random, apenas fiz questão de te dizer que tentaste ser engraçado mas falhaste, just that.

**Comment by ThisAintMeSilver** [comment]
Nunca soube a tua pword da DB. Nunca precisei, na altura tinha acesso a DB com uma conta minha. Conseguia ver a DB relacionada com o website, onde tinhas as coisas organizadas. Via quando o Liner tentava fazer merda e comprar items sem precisar de donation points, conseguia ver até uma pequena parte lá que tinha as passwords escritas por extenso, nomes de utilizador, perguntas para recuperar a conta e respostas para as perguntas. Algo relacionado com contas sem confirmação email? Foi a 3 ou 4 anos.

Se já conseguiste arranjar o problema de as motas darem a volta a isso, bravo. A screenshot foi tirada na altura que escrevi aquilo no entanto. Espero que o fix tenha sido posterior.

**Comment by silvermcd123** [comment]
btw o willier fez questão de dar upload das dbs para a net, tu aproveitaste-te disso, não lhe perguntaste nada apenas fizeste download e até acredito que ainda a tenhas. quando tu eras gm, o servidor não era este, nem nada relacionado a este! areia para tapar olhos a quem? 0. Lembraste-te disso á ultima da hora e sim, por acaso esta acc tinha a mesma passe, mas isso n quer dizer q eu partilhe a mesma passe com todas as contas, para nao falar que se tiveste acesso a isto reparaste a quantidade de merdas antigas q tenho aqui. e se não percebeste a parte do 1991, realmente tens um brain-bug. agora já chega de inventares merdas para mostrares q és pro ou 1337 ou pseudo-hacker que isto não é um concurso de medir pilas.

**Comment by ThisAintMeSilver** [comment]
Tens razão, não é um concurso de tal coisa.
