### ISSUE TITLE
Website - Logins com google+/facebook etc

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#12]
Possibilidade de registo e login com redes sociais

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
