### ISSUE TITLE
Quest  [The Fel and the Furious] Horde

### ISSUE THREAD

**Issue by Xerotom** [silvermcd123/WOWPT#124]
Objectives
Use a **Fel Reaver Control Console** to take control of a Fel Reaver Sentinel. Destroy 60 Deathforged Infernals before your fel reaver fails. When your mission is complete, report to Nakansi at Invasion Point: Cataclysm.

Deathforged Infernal destroyed (60)

Do lado da Horde não tem o **Fel Reaver Control Console**,do lado da allie tem para sendo da Horde não da para usar!

**Comment by ghost** [comment]
Fixed
