### ISSUE TITLE
Glyph  [Glyph of Voidwalker] 

### ISSUE THREAD

**Issue by Xerotom** [silvermcd123/WOWPT#127]
Boas

Este Glyph não esta a fazer o seu efeito!!não adiciona nada.

Obg

**Comment by silvermcd123** [comment]
Qual era o efeito que deveria fazer?

**Comment by Xerotom** [comment]
Boas


Devia dar +20% de vida ao voidwalker e não da nada..


https://wow.gamepedia.com/Glyph_of_Voidwalker


________________________________
De: SilveR <notifications@github.com>
Enviado: segunda-feira, 31 de julho de 2017 16:57
Para: silvermcd123/WOWPT
Cc: Xerotom; Author
Assunto: Re: [silvermcd123/WOWPT] Glyph [Glyph of Voidwalker] (#127)


Qual era o efeito que deveria fazer?
