### ISSUE TITLE
Shattered Sun Pendant of Restoration num druid

### ISSUE THREAD

**Issue by Gpkhaos** [silvermcd123/WOWPT#128]
Shattered Sun Pendant of Restoration - http://www.wowhead.com/item=34677/shattered-sun-pendant-of-restoration

nao proca num druid 

ja testei em min e em outro em party e sem party

todos os heals possiveis

agradecia o fix se possivel

sei que proca em shaman e preist e num druid e pala n ta a dar na rep de **the Scryers**

**Comment by silvermcd123** [comment]
proca noutra classe?

**Comment by Gpkhaos** [comment]
sei que proca em preist e num druid e num pala holy n ta a dar

**Comment by Broker-Precision** [comment]
This works,
Aldor Proc: Light's Salvation
Scryer's Proc: Arcane Surge
