### ISSUE TITLE
[Item]Molten Tabard

### ISSUE THREAD

**Issue by Psychh** [silvermcd123/WOWPT#129]
ID tabard: 1231231

Problema:
O efeito desta tabard especial que foi o reward de REALM FIRST MOLTEN CORE está a durar apenas alguns segundos. 

Como devia funcionar: 
O efeito: chamas, devia ficar sempre ativo, tal como a tabard Wowpt NotSoEpic Tabard.

Plz fix it. 

Thanks, 
Psych

**Comment by jQuery69** [comment]
Bunp

**Comment by romulopina** [comment]
Subscrevo

**Comment by ghost** [comment]
Fixed
