### ISSUE TITLE
Website - Bot anti-spam no registo

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#13]
Bot anti-spam no registo para evitar spam na db.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
