### ISSUE TITLE
Libram: Savage Gladiator's Libram of Justice 

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#133]
Boa tarde

O libram de pvp em questão, não tem qualquer utilidade visto não ter nenhum efeito de equip.
Este item deveria ter como equip '' Equip: Increases spell power of Flash of Light by 204. ''

Obrigado,
Hyperonimus

**Comment by silvermcd123** [comment]
https://wotlk.evowow.com/?item=42612

não indica qualquer efeito... onde viste isso?

EDIT:
http://wowwiki.wikia.com/wiki/Savage_Gladiator%27s_Libram_of_Justice aqui sim.
Já agora, a descrição não deu para perceber á primeira o problema em si. uma screenshot teria ajudado e provavelmente ajudaria a fixar mais rápido o problema.

**Comment by silvermcd123** [comment]
Corrigido

**Comment by ghost** [comment]
Julguei ter sido explicito, o problema era esse mesmo, não ter nenhum efeito. 
De qualquer das formas, obrigado.
