### ISSUE TITLE
Quest - The Mist Isn't Listening

### ISSUE THREAD

**Issue by pedromcrc** [silvermcd123/WOWPT#134]
http://www.wowhead.com/quest=12538/the-mist-isnt-listening
https://www.youtube.com/watch?v=bhkN45brNpc

Zepik quer que você mate 12 Gorlocs Brumurmúria.
Se perder a Trompa de Caça de Zepik, fale com o Ancião Harkek, no Morro dos Feralma

Problema: Dá para dar target nos mobs mas não dá para atacar. Na tab reputation nem aparece "At War"

Segue print em anexo
![wowscrnshot_081117_195735](https://user-images.githubusercontent.com/23343099/29228366-5bff26e0-7ed1-11e7-96a2-f8cc70051a65.jpg)

**Comment by silvermcd123** [comment]
Corrigido
