### ISSUE TITLE
Quest - Thrusting Hodir's Spear

### ISSUE THREAD

**Issue by pedromcrc** [silvermcd123/WOWPT#135]
http://www.wowhead.com/quest=13003/thrusting-hodirs-spear
https://www.youtube.com/watch?v=Jlhygv5swDU

Use a Lança de Hodir para desafiar a Wyrm Selvagem no Vale dos Antigos Invernos. Uma vez iniciado o combate, vocês lutarão até a morte

Problema: Ao usar o item "Spear" fica em cooldown e nunca funciona

Segue print em anexo
![wowscrnshot_081117_202334](https://user-images.githubusercontent.com/23343099/29228947-ce313f62-7ed3-11e7-9526-8fc4551cf3ff.jpg)

**Comment by silvermcd123** [comment]
Fixed
