### ISSUE TITLE
Quests que o NPC (Ricket em Storm Peaks) não tem

### ISSUE THREAD

**Issue by pedromcrc** [silvermcd123/WOWPT#136]
http://wowwiki.wikia.com/wiki/Quest:Expression_of_Gratitude

Este NPC não tem quests, segundo o link acima devia ter a quest chain.

Segue print em anexo do NPC sem quests e do quests completist com as quests que não tem lá.
![wowscrnshot_081117_204059](https://user-images.githubusercontent.com/23343099/29229305-7d7fc834-7ed5-11e7-8d5e-d48cbef8a5e3.jpg)

**Comment by silvermcd123** [comment]
A base de dados indica que para acederes a essa quest tens q completar
https://wotlk.evowow.com/?quest=12822

**Comment by silvermcd123** [comment]
@pedromcrc indica qual é a proxima quest q deverias ter exatamente.

**Comment by pedromcrc** [comment]
Ontem fui ao local com uma char nova e para confirmar tirei as prints todas.
Ao falar com ricket só tinha 2 quests.
![wowscrnshot_081917_125107](https://user-images.githubusercontent.com/23343099/29494654-e994a80a-85a6-11e7-866b-d9fc483d1eb7.jpg)
Fiz as duas quests e entreguei.
1ª Quest - When All Else Falls
![wowscrnshot_081917_132329](https://user-images.githubusercontent.com/23343099/29494657-1c5cfe40-85a7-11e7-9020-f3990276ec74.jpg)
![wowscrnshot_081917_132332](https://user-images.githubusercontent.com/23343099/29494662-226121ae-85a7-11e7-9e0f-9d3152b21d07.jpg)
![wowscrnshot_081917_132336](https://user-images.githubusercontent.com/23343099/29494665-28aaf9cc-85a7-11e7-9cf8-7ff58522609e.jpg)
E depois entreguei a 2ª quest - Reclaimed Rations
![wowscrnshot_081917_132509](https://user-images.githubusercontent.com/23343099/29494671-441e8d9a-85a7-11e7-86b6-196304e32dcc.jpg)
![wowscrnshot_081917_132513](https://user-images.githubusercontent.com/23343099/29494673-486e67f8-85a7-11e7-83d6-90c2880181c4.jpg)
![wowscrnshot_081917_132518](https://user-images.githubusercontent.com/23343099/29494675-4be3bc30-85a7-11e7-8755-32b02a4bea63.jpg)
![wowscrnshot_081917_132522](https://user-images.githubusercontent.com/23343099/29494676-4f037f04-85a7-11e7-9948-6ec480d9f7b4.jpg)
Tal como está nas printscreens o ricket não me deu mais nenhuma quest da quest chain.

**Comment by Broker-Precision** [comment]
Not an issue
