### ISSUE TITLE
Quest loot shining objetcs

### ISSUE THREAD

**Issue by Krork** [silvermcd123/WOWPT#147]
Em algumas quests em que é necessário abrir chests e/ou carregar em items em que se faz channeling para abrir, o item que se tenta abrir fica com bug, no qual não aparece conteúdo e impossibilita abrir de novo (diz que ja esta em uso), embora continue a brilhar como se estivesse pronto a utilizar. Em quests em que é necessário ir buscar um unico item, tipo a quest "the vile reef" em stranglethorn valley, em que me deu este bug, so apos server restart e que consegui abrir novamente o conteudo do item. Este bug tambem ja me aconteceu em outras quests a low level.

**Comment by ghost** [comment]
Não consigo reproduzir. Preciso de mais informação. Poderá ter sido devido a lag

**Comment by Krork** [comment]
Devido à lag consigo garantir que nao foi... Aconteceu me 2 vezes, sendo que a ultima foi na quest mencionada acima. Foi ao sitio da quest onde é suposto carregar e vai abrir o item... O bug que aconteceu fez com que no final de preencher a barrinha de abrir, simplesmente não apareceu nada... Ao carregar novamente no item para abrir apenas diz que o item ja esta a ser utilizado impossibilitando abrir o mesmo.

**Comment by ghost** [comment]
@Krork  Possivelmente foi do lag, existe uma grande probabilidade. Acabei de testar, funcionou perfeitamente. Obrigado pelo report !
