### ISSUE TITLE
Arathi Basin capture point flags

### ISSUE THREAD

**Issue by Kalmageddon** [silvermcd123/WOWPT#148]
Flags de AB as vezes nao dao spawn para um dos lados, o que drasticamente reduz as chances de ganhar a battleground.
Notei que se, por ex, se sendo horde e nao houver as flags, mas a alliance as tem, se eles derem cap, ai sim ja da para ver e contestar...

**Comment by ghost** [comment]
Confirmado. No entanto, é um bug muito difícil de reproduzir. Já vi acontecer in-game mas é muito aleatório.

**Comment by silvermcd123** [comment]
este bug é um bocado random. testei e não consigo reproduzir.
