### ISSUE TITLE
Website - Timers countdown do estilo dos que estao nos eventos para o sistema de votos

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#15]
Timers countdown do estilo dos que estao nos eventos para o sistema de votos

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
