### ISSUE TITLE
Seal of Command no proc on judgement

### ISSUE THREAD

**Issue by Kalmageddon** [silvermcd123/WOWPT#152]
Seals deviam procar de (physical) attacks, inclui auto attack, crusader strike, divine storm e judgement. 
Neste momento, funciona corretamente com seal of righteousness, mas com o seal of command, no judgement nao da a proc do seal.

Uns prints para verificarem.

https://imgur.com/a/WkiDJsJ

**Comment by ghost** [comment]
Mais info: http://wowwiki.wikia.com/wiki/Seal_of_Command_(old)

**Comment by Kalmageddon** [comment]
ty jQ - realmente devia ter colocado isso xD

**Comment by jQuery69** [comment]
Eu confirmei depois de ter visto este video. 
https://www.youtube.com/watch?v=EolxL4nrDEE

No entanto após um teste parece-me que o judgement está certo. Poderei estar errado porque não é  a minha main

![image](https://user-images.githubusercontent.com/41009055/42761559-cb845032-8905-11e8-8cdb-25ec3b2dff27.png)

Ele devia de dar outro hit ? 

No video parece-me que sim, mas a tooltip diz 

> Unleashing this Seal's energy will judge an enemy, instantly causing 0.19*mw+0.08*AP+0.13*HolP to 0.19*MW+0.08*AP+0.13*HolP Holy damage.

**Comment by ghost** [comment]
Eu confirmei depois de ter visto este video. 
https://www.youtube.com/watch?v=EolxL4nrDEE

![image](https://user-images.githubusercontent.com/41009055/42761559-cb845032-8905-11e8-8cdb-25ec3b2dff27.png)

Não aparece o hit do seal

Related: https://github.com/TrinityCore/TrinityCore/issues/447

**Comment by ghost** [comment]
Re aberto devido ao bug que o fix gerou

**Comment by ghost** [comment]
Fixed
