### ISSUE TITLE
Warlock PvP Fears e Death Coil

### ISSUE THREAD

**Issue by romulopina** [silvermcd123/WOWPT#153]
Quando uso fear ou death coil nos players eles ficam parados no mesmo sitio durante esse periodo de tempo até o debuff acabar, e nao consigo atacar até o debuff acabar, quando acaba eles fazem tipo teleport para um lugar proximo.

Já agora peço para verificarem o fel intellegence do fel hunter, nem sempre funciona e já aconteceu tambem com o blood pact do imp.

- [x] Death Coil

- [x] Fear

- [x] Buffs

**Comment by ghost** [comment]
Após uns testes feitos com o Monkas verificamos que os buffs, estão todos correctos. 

O issue dos death coil e fear também não se verificou. Vou fechar por agora.

**Comment by ghost** [comment]
Reopened por causa da situação do stacking dos buffs em raid. Verificar as regras dos buffs

**Comment by Psychh** [comment]
O bug do fear é verdade e já existe á anos.
Um gajo as vezes da fear, começa a castar uma merda qualquer e passado um bocado afinal o gajo ta atras de nos.

**Comment by ghost** [comment]
@Psychh  poderá ser um problema do server e do movimento do fear

**Comment by silvermcd123** [comment]
https://github.com/TrinityCore/TrinityCore/issues/9475

**Comment by ghost** [comment]
@silvermcd123  check https://github.com/TrinityCore/TrinityCore/pull/13095

**Comment by silvermcd123** [comment]
foi aplicado um fix. testem e vejam como está.

**Comment by romulopina** [comment]
Parece estar bom agora @silvermcd123

**Comment by ghost** [comment]
Parece estar fixed!
