### ISSUE TITLE
Warlock PvP Bonus Set

### ISSUE THREAD

**Issue by romulopina** [silvermcd123/WOWPT#156]
5 peças equipadas e não dá o bonus que reduz fear cast, parou de funcionar à pouco tempo
https://imgur.com/a/jLYYAnv

**Comment by Psychh** [comment]
Os titulos devem estar relacionados com as crossfaction bgs. Por ex quando vais ally.

**Comment by silvermcd123** [comment]
façam reports em issues separados sff. assim nao dá.

**Comment by jQuery69** [comment]
**Precisas de 4 peças para ativar o bonus, só tens 3**

**Comment by jQuery69** [comment]
Não confirmado, os items que tens são de sets diferentes

**Comment by ghost** [comment]
Confirmado. Alguns items não estão a contar para o set https://wotlk.evowow.com/?itemset=345 porque este set é o antigo do classic, e não o set normal do wrath. Alguns items poderão não ter os ids certos.

**Comment by romulopina** [comment]
Mas já esteve tudo a funcionar, eu já tive o bonus do fear, isto foi recente, se tiver nas bags diz que funciona mas quando equipo ele sai

**Comment by ghost** [comment]
Eu não fiz alterações recentemente, teremos de investigar
