### ISSUE TITLE
Titulos PvP

### ISSUE THREAD

**Issue by romulopina** [silvermcd123/WOWPT#157]
Há um pequeno bug com os titulos pvp, às vezes tou como First Seargent e depois do nada fico sem titulo e quando vou selecionar um está la apenas seargent major, penso que aconteçe depois de uma bg, nem sempre.

**Comment by ghost** [comment]
Quando fazes relog, o que acontece?

**Comment by romulopina** [comment]
Nada, isto aconteçeu ainda ontem antes de entrar na bg estava como first seargent (como sou horde, é o titulo correcto) depois quando acabou a bg fiquei com seargent major (versão alliance) penso que o psych esteja certo, essa bg talvez estava a jogar como ally e ficou como seargent major, para mudar penso que tenho que fazer uma bg e jogar como horde.

**Comment by ghost** [comment]
Quando fazes uma BG as horde, fica correto ?

**Comment by romulopina** [comment]
Sim, bastou matar um ally que mudou logo para first seargent

**Comment by ghost** [comment]
Este bug aparenta ser um bug visual. Após normalização das atividades fora do x-faction este fica resolvido. Vou fechar
