### ISSUE TITLE
Missing quests Lokhtos Darkbargainer

### ISSUE THREAD

**Issue by psico420** [silvermcd123/WOWPT#158]
O npc "Lokhtos Darkbargainer" (id 12944) devia de ter umas quests para trocar items por reputacao por exemplo Fiery core/Lava core etc etc, mas de momento nao aparece quest nenhuma nele. As quests sao importantes para levelar a reputacao com ele pa poder comprar recipes pa crafting. Vou deixar aqui o link de uma das quests que la devia estar, [www.wowhead.com/quest=6643/favor-amongst-the-brotherhood-fiery-core].

**Comment by ghost** [comment]
Obrigado pelo teu report Psico, vamos averiguar a situação !
