### ISSUE TITLE
Os pets dos npcs não atacam quando o owner é atacado

### ISSUE THREAD

**Issue by Hugarada** [silvermcd123/WOWPT#159]
https://classicdb.ch/?quest=871

Este NPC tem um wolf a acompanhalo que supostamente ao provoca-lo ele iria mandar o seu pet ir contra porem ele não faz nada, n tem sequer uma IA a não ser seguir o dono
![wowscrnshot_072618_134410](https://user-images.githubusercontent.com/41742543/43263232-9270b5ce-90da-11e8-8015-b1c02e194dcc.jpg)

**Comment by ghost** [comment]
Confirmado, o pet não ataca. No entanto tem AI, faz cast de spells etc.

**Comment by silvermcd123** [comment]
é um issue, true. mas não é algo com tanta importância. no entanto, será fixado assim que os que teem mais gravidade estejam ok.
