### ISSUE TITLE
Website - Mostrar progressão ao clicar no conteudo atual

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#16]
Ao clicar no progresso na página principal abrir um timeline de todas as raids completas e pelas respetivas guilds e membros.

**Comment by ghost** [comment]
Isto vai requerer duas novas tabelas:
- Deteção de bosses que dão realmfirst
- Guilds e membros que completaram o realmfirst

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
