### ISSUE TITLE
Bug's em Quest

### ISSUE THREAD

**Issue by DMBoss** [silvermcd123/WOWPT#160]
Esta quest http://www.wowhead.com/quest=8737/azure-templar não está a spawnar o NPC.

Nesta http://www.wowhead.com/quest=8309/glyph-chasing o Hive'Regal não está nas coordenadas.

**Comment by Psychh** [comment]
A primeira nao percisas porque os items dropam nos silithid em silithus.

E a segunda ta a funcionar que eu já a fiz, ve um video do youtube para veres onde é.

**Comment by jQuery69** [comment]
Confirmado

**Comment by ghost** [comment]
Confirmado o comentário do @psychh no entanto vou melhorar as quests
