### ISSUE TITLE
Seal of Command - Seal proc

### ISSUE THREAD

**Issue by Kalmageddon** [silvermcd123/WOWPT#161]
A proc do seal of command anda esquesita, devia dar a cada crusader strike, auto attack e judgement. O bug nisto eh que, apesar de procar em todos os que em cima disse, se deres um auto logo depois de um judgement, um crusader, ou vice versa, a proc so da 1x em vez de procar por casa instancia de dano...

SS mostra 1 crusader strike, 1 auto attack, e apenas 1 seal of command proc.

Com o seal of righteousness isso nao acontece (AKA works as intended)

![wowscrnshot_073018_232602](https://user-images.githubusercontent.com/920335/43427343-0f4ba65c-9451-11e8-90cc-0f623c39ada4.jpg)
![wowscrnshot_073018_233244](https://user-images.githubusercontent.com/920335/43427344-0f6b2b4e-9451-11e8-8cf6-818317f4569a.jpg)

**Comment by ghost** [comment]
O fix que apliquei anteriormente corrigiu os procs. No entanto parece existir aí um icd

**Comment by Kalmageddon** [comment]
Apesar de ja o ter feito... Checka os prints que tambem coloquei ai btw
Da para ver que ta a faltar qualquer coisa no print relativo ao seal of command...

**Comment by ghost** [comment]
@Kalmageddon  fixei no PTR, no entanto é necessário dar reload as tables in-game. Quando puderes faz um teste

**Comment by ghost** [comment]
Fixed
