### ISSUE TITLE
[Item]Agent of Nozdromu

### ISSUE THREAD

**Issue by Psychh** [silvermcd123/WOWPT#162]
[Agent of Nozdromu](https://db.rising-gods.de/?item=20402)
Ter o item na bag devia permitir o loot de [Silithid Carapace Fragment](https://db.rising-gods.de/?item=20384), o que não acontece.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/41009055/43595258-2208237c-9674-11e8-8763-e01b0fc6de40.png)

No PTR consigo @Psychh, estás em que quest?

**Comment by Psychh** [comment]
Não estou em quest nenhuma o Kalma deu-me deputize para farmar para ele. Ao ter o item na bag devia conseguir.

**Comment by ghost** [comment]
Confirmado
