### ISSUE TITLE
Skills de hunter bugados

### ISSUE THREAD

**Issue by Arroow** [silvermcd123/WOWPT#166]
arcane shot bugado da cerca de 200 de dano em survival , e wyvern string nao da cc e tem range elimitado .

**Comment by jQuery69** [comment]
O spell que tu tens, é um id que não devias de ter.

Quando puderes envia prints da prova do arcane shot.

Não confirmado.

A Seg, 13 de ago de 2018, 19:20, Arroow <notifications@github.com> escreveu:

**Comment by ghost** [comment]
@Arroow  por favor envia-me algo que suporte o arcane shot. Alguma screenshot da tooltip e do recount

Bugs confirmados:

- [ ] Arcane Shot

- [x] Wyvern Sting 

Corrigidos

- [ ] Arcane Shot

- [x] Wyvern Sting

**Comment by ghost** [comment]
Fixed. Não se verificou o bug do arcane shot.
