### ISSUE TITLE
[BWL][Boss]Vaelastrasz - So dropa 1 item.

### ISSUE THREAD

**Issue by Psychh** [silvermcd123/WOWPT#167]
[Vaelastrasz the Corrupt](http://wowwiki.wikia.com/wiki/Vaelastrasz_the_Corrupt)
https://db.rising-gods.de/?npc=13020#drops

Problema: Só está a dropar 1 item.

Como devia funcionar: Devia dropar +.       (2? (tier + item)) idk.

Cumps,
Psych

**Comment by ghost** [comment]
Confirmado

**Comment by ghost** [comment]
Fixed
