### ISSUE TITLE
Dungeons - Bosses: Imunidades

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#19]
Falta imunidade de interrupt nos bosses (talvez outras? untested)

**Comment by barrotes** [comment]
drop de emblms perfeitamente normal

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
