### ISSUE TITLE
Quest - Fire at will!

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#25]
Ao usar o item naturalized ammunition não dá para controlar o fel cannon.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue.
