### ISSUE TITLE
Quest - The Big Bone Worm

### ISSUE THREAD

**Issue by Zycur** [silvermcd123/WOWPT#29]
Quando matamos um Clefthoof e tocamos o tambor, o corpo desaparece mas a minhoca não faz spawn

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
No issue
