### ISSUE TITLE
Quest - Dimensius The All-Devouring

### ISSUE THREAD

**Issue by Zycur** [silvermcd123/WOWPT#30]
Para começar a quest tem que se falar com o capitão, mas quando se fala com ele não há nenhuma opção para a começar.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue
