### ISSUE TITLE
Quest - Troublesome Distractions

### ISSUE THREAD

**Issue by Zycur** [silvermcd123/WOWPT#31]
Fala-se com o gajo, mas não há nada para interagir, idêntico ao Dimensius The All-Devouring.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue
