### ISSUE TITLE
Quest - Sabotage the Warp-Gate

### ISSUE THREAD

**Issue by Zycur** [silvermcd123/WOWPT#32]
Again, falas com o gajo, mas não há nada para começar o evento.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Fixed
