### ISSUE TITLE
NPC - Runetog Wildhammer

### ISSUE THREAD

**Issue by GazelleMag** [silvermcd123/WOWPT#33]
Este npc é um fly master que não funciona. Encontra-se em Hellfire Peninsula, Shatter Point.
![screenshot_3](https://cloud.githubusercontent.com/assets/23154979/20033352/61ab2a60-a396-11e6-8d2c-038a53a8f8c4.png)

**Comment by ghost** [comment]
não poderá ser por causa de estares com GM on? algum player reportou isto?

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Fixed
