### ISSUE TITLE
Dungeon - Mechanar HC

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#34]
http://wowwiki.wikia.com/wiki/Cache_of_the_Legion

"The Cache of the Legion is a "chest" found in The Mechanar, one of the 4 instances in Tempest Keep. It is located next to the elevator that leads to the second floor. It is locked and unpickable so you must use the [Cache of the Legion Key] to open it. The key can be created by combining the Jagged Red Crystal and Jagged Blue Crystal which are looted from Gatewatcher Gyro-Kill and Gatewatcher Iron-Hand."

Problema: Em Heroic os mobs não dropam os crystals(chave), nem está lá o "cofre" presente.

A diferença de loot para normal é dropar um badge of justice.

Cumps.

**Comment by Psychh** [comment]
Os 2 mobs Gatewatcher Gyro-Kill and Gatewatcher Iron-Hand. Não estao a dropar os crystais.

**Comment by barrotes** [comment]
not fixed falta os cristais nos mobs em hc

**Comment by Psychh** [comment]
8 days still no crystals

**Comment by ghost** [comment]
Problema: o loot pedia quest como requerimento. Provavelmente algo falhou na investigação. de qualquer maneira tirei o requerimento e está agora fixed.
