### ISSUE TITLE
Website - Estilos para os diferentes game-world events

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#40]
Aplicar estilos especiais no site sempre que um world event esteja ativo, ex: Day of the dead... Winter veil... etc

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
