### ISSUE TITLE
Quest - Trial of the Naaru:Tenacy

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#41]
Ao terminar a dungeon espera-se que o npc faça algo e nada acontece.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
