### ISSUE TITLE
Quest - The Ballad of Oldie McOld

### ISSUE THREAD

**Issue by Wreakhavoc23** [silvermcd123/WOWPT#43]
http://www.wowhead.com/quest=11064/dragonmaw-race-the-ballad-of-oldie-mcold

Boas, esta quest não está a funcionar de maneira nenhuma, dps de falar cm o npc e aceitar a quest, ele simplesmente não se mexe nem interage, msm abandonando e voltado a pegar na quest.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One
