### ISSUE TITLE
Quest - Turning Point

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#57]
Ele nao ataca nem da para atacar, ao usar o item da quest diz invalid target.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue
