### ISSUE TITLE
[Item Bug] Alchemit's Stone!!

### ISSUE THREAD

**Issue by eldunari** [silvermcd123/WOWPT#63]
Boa tarde, fora o trinket de eye of gruul existe mais um essential para healers recuperarem MANA! bugado

Alchemist's Stone: http://wowwiki.wikia.com/wiki/Alchemist's_Stone

O que devia fazer: Aplicar Aura http://wotlk.openwow.com/spell=17619 ao player e aumentar a regeneraçao de mana e de hp das potions.

O que esta a fazer: Efetivamente esta aplicar a aura mas não está a aumentar nada... testei isto com uma fel mana potion. 

Teste do Bug: Fel Mana Potion (http://wotlk.openwow.com/item=31677) 3200 de mana over 24 secs (400 mana over 3 secs)... ora se adicionarmos os 40% (1280 no caso da Fel  Mana Potion  seria 4480 over 24secs... segundo consta no wikki e passo a citar: " Using this trinket in conjunction with [Fel Mana Potion] grants a restoration of 4480 mana over time at the cost of a slight debuff..."

Edited: Morrer com alchemist's stone remove a aura! nao deveria acontecer isso a partir do momento que o trinket esta equipado a aura devia estar sempre up!

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue, Can see via combat log that additional mana is given.
