### ISSUE TITLE
[Aura/Spell Bug] Replenishment

### ISSUE THREAD

**Issue by eldunari** [silvermcd123/WOWPT#64]
Boa Noite

Replenishment: http://wowwiki.wikia.com/wiki/Replenishment ::: http://wotlk.openwow.com/spell=57669

O que devia fazer: Regenerar 1% da Mana do player a cada 5 segundos durante 15 segundos totais... entre outras palavras 3% maximum mana durante os 15 segundos!

O que realmente acontece: o replenishment nao esta a regenerar os 3% totais

Explicaçao do bug e testado: Ora o meu mage tem 8621 de mana... 3% da sua mana é algo como: (8621 * 3) / 100 = ~259, ou seja o valor recuperado durante os 15 segundos... ora vejamos o que acontece ao replenishment segundo o msbt (MilkScrollingCombatText):
-> 12 ticks de replenishment
-> 1 tick: 17 mana 
-> 3 ticks: depois 51de mana
-> 4 ticks: depois 68 de mana
-> 4 ticks: depois 68 de mana
e o buff termina sem dar os 3 ticks finais. Se formos a ver 17(17,242 para ser mais preciso) mana de cada tick é os ditos 0,20% per 1 sec  do maximo de mana que pervalece um total de 85 (86,21 para ser mais preciso) de mana por 5 seconds até aqui tudo bem agora somemos os ticks todos:

Total de Mana: 17+51+68+68 = 204 
Total de Ticks: 1+ 3 + 4 +4 = 12 

Ora 204 esta muito longe dos ~259 de mana que o replenishment supostamente deveria de dar.

Cumpz 
PS: espero que tenham percebido o Bug

**Comment by eldunari** [comment]
PRIORIDADE BAIXA!? tu sabes oh menos para que serve o replenishment? sabes o quanto a existencia dele afeta uma raid e quanto esses 3 ticks por 15 secs durante uma fight inteira conta para o regen de mana das classes? enfim nd muda

**Comment by ghost** [comment]
Boas, temos prioridades de bugs mais graves de momento. Primeiro é preciso entender se realmente o que indicas é bug, sendo que és o unico a reportar temos que investigar tudo primeiro e de seguida, o fix propriamente dito não é fácil, se for como estou a pensar. Enfim, há coisas á frente primeiro. Obviamente que gostariamos de ter tudo fixed, mas não é possivel.

**Comment by ghost** [comment]
Não confirmado
