### ISSUE TITLE
Quest - The Exorcism Of Colonel Jules

### ISSUE THREAD

**Issue by lucasbehs** [silvermcd123/WOWPT#65]
Hellfire Peninsula
The Exorcism Of Colonel Jules: O exorcismo termina mas a busca não é concluída.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
