### ISSUE TITLE
Quest - Gauging the Resonant Frequency

### ISSUE THREAD

**Issue by lucasbehs** [silvermcd123/WOWPT#66]
Blade's Edge Mountains
Gauging the Resonant Frequency: Os osciladores não funcionam.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue
