### ISSUE TITLE
Lista de buscas pela Ally com erros em seus respectivos mapas: 13

### ISSUE THREAD

**Issue by lucasbehs** [silvermcd123/WOWPT#68]
Hellfire Peninsula: 1
1: "The Exorcism Of Colonel Jules" O exorcismo termina mas a busca não é concluída.

Zangarmarsh: 0

Terokkar Forest: 0

Nagrand: 0

Blade's Edge Mountains: 3
1: "Gauging the Resonant Frequency" os osciladores não funcionam.
2: "Whispers of the Raven God" 3 das profecias funcionam mas a quarta não.
3: "Fire At Will!" os canhões e portais não funcionam corretamente.

Netherstorm: 7
1: "It's a Fel Reaver, But with Heart" é possível matar o mob mas impossível de se pegar o loot para completar a quest.
2: "Sabotage the Warp-Gate!" o npc fica parado e não inicia suas funções.
3: "Escape from the Staging Grounds" o npc fica parado e não inicia seu caminho de volta para a base.
4: "Dimensius the All-Devouring" é impossível conversar com o capitão Saeed para iniciar a busca.
5: "Delivering the Message" o npc faz tudo corretamente, mas no final a busca não se completa.
6: "Troublesome Distractions" é impossível conversar com o npc.
7: "An Apexis Relic" impossível inserir os Apexis Shard.

Shadowmoon Valley: 2
1: "The Fel and the Furious" os controles não funcionam.
2: "Thwart the Dark Conclave" não se pode cancelar o ritual.

**Comment by ghost** [comment]
Por favor reporte tudo em issues separados... assim é impossivel
