### ISSUE TITLE
Quest - Lost In Action

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#7]
Não é possivel usar o gossip para completar um dos passos da quest

https://scontent-mad1-1.xx.fbcdn.net/v/t34.0-12/14877935_1572803816078802_1753490671_n.png?oh=63df7d01f201350c0534cfe8e4430197&oe=5817F7A0

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue
