### ISSUE TITLE
Quest - Dragonmaw Race: The Ballad of Oldie McOld

### ISSUE THREAD

**Issue by cannibalize** [silvermcd123/WOWPT#70]
**QuestID: 11064 /Shadowmoon Valley, Netherwing Ledge**
**Dragonmaw Race: The Ballad of Oldie McOld**: Quando-se aceita a missão do NPC: [**Murg "Oldie" Muckjaw**] (**ID: 23340**), supostamente, este deveria se mexer e começar uma "corrida" mas ele simplesmente, não faz nada.

**Comment by ghost** [comment]
Duplicado https://github.com/silvermcd123/WOWPT/issues/43
