### ISSUE TITLE
Boss Fanthom-Guard Sharkkiss - Falta de Spell

### ISSUE THREAD

**Issue by barrotes** [silvermcd123/WOWPT#72]
Boss Fanthom-Guard Sharkkiss spell Beast Within crashava o servidor.
Retirado a habilidade (needs fix)

**Comment by ghost** [comment]
Confirmado no boss Fanthom-Guard Sharkkiss (crashlogs)

**Comment by ghost** [comment]
Causa do Crash : Spell Beast Within e Enrage casted no pet

- Removido temporáriamente até haver fix definitivo de modo a evitar futuros crashs

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
