### ISSUE TITLE
Crash - Instance Warning

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#73]
Servidor crasha habitualmente ás 4 da manhã quando tenta avisar os players que todas as instances deram reset.

(Crashlog existente)

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
