### ISSUE TITLE
Boss - The Lurker Below

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#74]
Boss não dá engage com os players
- [x] Achievement
- [x] Boss engage
- [ ] Spout: The Lurker shoots a spray from his mouth at his current target then slowly rotates 360+ degrees in a clockwise or counter-clockwise direction. (rodar e knockback)

http://wowwiki.wikia.com/wiki/The_Lurker_Below

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
