### ISSUE TITLE
Pot Abuse nas Battlegrounds

### ISSUE THREAD

**Issue by Niteshade1** [silvermcd123/WOWPT#75]
Desde que um inteligente qualquer descobriu que se podia usar "Potion of Petrefication" nas battlegrounds o pessoal começou a ver e a fazer toda a gente igual, tornando-se assim um bug abuse pois não devia ser possível usar isso numa BG.
Por favor arranjem alguma maneira de proibir o uso disso em sítios de pvp. 

cump,
Obrigado

**Comment by Psychh** [comment]
Ta a funcionar blizzlike.

**Comment by ghost** [comment]
por favor indica algum local fidedigno que indique que isto realmente seja um bug

**Comment by eldunari** [comment]
Não é nenhum abuso as potions sempre foram autorizadas em bgs ate flasks! por isso senao queres que isto aconteça da join em arenas  e para de whinnar por veres players feitos estatuas... mas que acabam por ter inteligencia...  Fica algumas dicas de items que podes usar em pvp/bgs: http://www.wow-one.com/forum/topic/45665-useful-items-for-pvp-mainly-battlegrounds/

**Comment by ghost** [comment]
Retirados drops da keg
