### ISSUE TITLE
Ntherwing Ledge ~Bugged

### ISSUE THREAD

**Issue by Taurii** [silvermcd123/WOWPT#78]
All Netherwing Ledge is bugged. I did the chain to unlock it I got to exalted and then when I try to get the other quests I can't it's flagged!
![wowscrnshot_121216_204651](https://cloud.githubusercontent.com/assets/23378952/21116104/2b374076-c0ac-11e6-93fd-4ccf6320de3b.jpg)
Okay so I need the other skill of flight to get it please close this =/

**Comment by eldunari** [comment]
Não testado então o moço ta revered e ta em netherwing ledge sem a aura que lhe da friendly e disfarce de orc.... E DIZES QUE NAO ESTA TESTADO! Abram os olhos foda-se!

**Comment by eldunari** [comment]
E Btw não é um bug de QUEST! é de Aura/Zone a aura http://wotlk.openwow.com/object=181281 Falta atribuir isto ao player sempre que entra na zona depois de completar a quest http://www.wowhead.com/quest=10870/ally-of-the-netherwing e é perfeitamente visivel na print que ele nao tem a aura e ja completou a quest de outra maneira nao estaria revered!

**Comment by silvermcd123** [comment]
@eldunari  peço que moderes a tua linguagem, ninguem aqui é pago para fixar, o "não testado" é apenas uma tag que significa "não testado pela staff" não quer dizer q não seja bug, apenas não foi testado ao pormenor e outros detalhes podem surgir.

**Comment by eldunari** [comment]
e que pormenores queres mais tu (essa coisa sempre teve fixed btw) ? sinceramente nao entendo ja a porcaria das plantas é a mesma merda 3h a volta de outland + 2h a acampar os supostos spots delas em vez de 20 havia 3 a 4 com respawns de horas em suma em 5h a apanhar plantas tive 10 manathistle que foram as primeiras que apanhei.... ou a minha char ta bugada ou as plantas so aparecem cada vez que dao release a content... depois querem que modere a linguagem.... enfim ta bom tem razao sua alteza e ja agora desculpe o off topic

**Comment by silvermcd123** [comment]
@eldunari  já reparaste no volume de bugs? por acaso foi um gm que tratou disso, tens que ter paciencia porque há pessoas aqui que me estão a ajudar, embora não tenham a experiencia toda , estão a aprender tb.

**Comment by Taurii** [comment]
Por favor eu só quero o meu dragão! D;

**Comment by Wreakhavoc23** [comment]
Se n me engano,é preciso Artisan Flying para o morph(o de 270%)

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue
