### ISSUE TITLE
Quests - Hallows End

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#8]
Quests de hallows end de apagar os fogos não funcionam, sem scripts.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
