### ISSUE TITLE
Bug - Morogrim Tidewalker

### ISSUE THREAD

**Issue by Zycur** [silvermcd123/WOWPT#81]
Earthquake

3000-4000 damage. 45-60 sec cooldown. 50 yard range.

Não faz este spell

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue
https://tbc.wowhead.com/spell=37764/earthquake
