### ISSUE TITLE
Implementação - Mute por account/ip

### ISSUE THREAD

**Issue by ghost** [silvermcd123/WOWPT#86]
- [ ] Implementar mute por account
- [ ] Implement mute por ip

**Comment by Psychh** [comment]
Depois diz que nao tens tempo para corrigir bugs assério...

**Comment by ghost** [comment]
@Psychh se isto tem que ser feito, é porque é um must devido ao mute pela char não ser efetivo. Só nós (staff) sabemos o porque disto ser importante (para evitar bans e afins) porque os jogadores levam mute numa char e vão para outra spammar. Isto não é uma coisa que estou a fazer de momento, só deixei aqui pendente para não me esquecer, como muitas outras coisas. Eu é que tenho que saber as prioridades, acabei de fixar TK, penso que tenho liberdade de ir colocando coisas que tenciono fazer. Isto não é bug mas tambem não disse que é o topo da minha lista, mas mais tarde ou mais cedo será util. Para não falar que isto são duas linhas de código, por isso é escusado estás a apontar-me o dedo sem saberes o que estas a falar.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
