### ISSUE TITLE
Quest - Felsworn Gas Mask

### ISSUE THREAD

**Issue by Gpkhaos** [silvermcd123/WOWPT#92]
##  **Não da para completar no npc devido a ele não estar no sitio **

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Not an issue
