### ISSUE TITLE
Bug - Hunter pet revive sem barra depois

### ISSUE THREAD

**Issue by Gpkhaos** [silvermcd123/WOWPT#93]
## Quando damos revive o pet ele vem mas a barra do pet não aparece
tenho de lhe fazer desmiss e call depois para aparece a barra dele

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico
