### ISSUE TITLE
Item - Orb of the Blackwelp!

### ISSUE THREAD

**Issue by GazelleMag** [silvermcd123/WOWPT#98]
Após usar o item não é possível fazer remove effect para voltar ao estado normal.

**Comment by silvermcd123** [comment]
Para uma maior liberdade no servidor podem todos utilizar, maior parte das ferramentas neste link nao sao detetaveis pelo anti cheat!

mega:#!JIJgnSTR!FYeAXbuukPyi57BAZVqmEkRzC20BQ89WGD93ZtRkSd8

Have fun

Cumpz The Beloved One & Toxico

**Comment by Broker-Precision** [comment]
Is displayed as a debuff instead of a buff.
